server:
  port: 9999

spring:
  application:
    name: API-GATEWAY
  cloud:  # 注册到nacos
    nacos:
      server-addr: localhost:8848
    gateway:
      routes: #断言 用来配置路由规则 id uri path
        #admins router
        - id: admins_router
          uri: lb://API-ADMINS #负载均衡写法【兼容集群写法】
          predicates:
            - Path=/admins/** #采用这种路径断言办法，请求进入网关断言，但是不能直接以这种方式发送给对应微服务的controller，因为没有此路径的请求，需要配合filters使用
          filters:
            - StripPrefix=1 # StripPrefix GatewayFilter(SpringCloud Gateway的内置路由过滤器)：去掉请求路由的前几级，即/admins/**会转换成/**
        #category router
        - id: categary_router
          uri: lb://API-CATEGORY #负载均衡写法
          predicates:
            - Path=/category/**
          filters:
            - StripPrefix=1 #去掉请求前缀的filter =写int类型 1代表去掉1级前缀 2代表去掉两级
        #users router
        - id: users_router
          uri: lb://API-USERS #负载均衡写法
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1 #去掉请求前缀的filter =写int类型 1代表去掉1级前缀 2代表去掉两级
        #videos router
        - id: videos_router
          uri: lb://API-VIDEOS #负载均衡写法
          predicates:
            - Path=/videos/**
          filters:
            - StripPrefix=1 #去掉请求前缀的filter =写int类型 1代表去掉1级前缀 2代表去掉两级

      globalcors: # 网关解决请求跨域问题
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
